# Generated by Django 4.2.7 on 2025-08-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="background",
            name="generated_image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="generated_image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="scene",
            name="generated_image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
